dist: trusty

language: php

php:
    - 7.2
    - 7.3

addons:
    sonarcloud:
        organization: "critterbots-github"

cache:
    directories:
        - $HOME/.composer
        - $HOME/.sonar
        - $HOME/.sonarscanner
        - $HOME/build/critterbots/lmcom-test/vendor

install:
    - travis_retry composer install

script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - git fetch --no-tags https://github.com/critterbots/lmcom-test.git +refs/heads/master:refs/remotes/origin/master
    - ./vendor/bin/phpunit
    - sonar-scanner
    - ./run-solution.sh
